baseurl = "https://mching.github.io"
publishDir = "../mching.github.io"
relativeurls = true
languageCode = "en-us"
# baseurl = "https://mching.github.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Dripping Data"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[Params]
  subtitle = "My numbers blog. It's not quite Flowing."
  logo = "img/IMG_6557.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  hideEntryNavigation = false
  builddrafts = false
  
[Author]
  name = "Mike Ching"
#  email = "youremail@domain.com"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "mching"
  twitter = "mikec2a"
#  reddit = "username"
  linkedin = "michael-ching-033a5029"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/michael-ching-033a5029"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/mikec2a"

[params]
    description = "My numbers blog."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

