---
title: Fax Problem at Work
author: ~
date: '2017-12-15'
slug: fax-problem-at-work
categories: R
tags: 
  - regular_expressions
---

```{r}
library(stringr)
library(lubridate)
library(dplyr)
library(ggplot2)

tmp_con <- file("./content/datasets/faxes_OCR.txt")
fax <- readLines(tmp_con)
close.connection(tmp_con)
rm(tmp_con)

fax


```


```{r}
# Get phone numbers
phoneset <- grep("[0-9]{7,}", fax) # index for lines with recognizable phone numbers
fax[phoneset] # inspect output
ph_numbers <- str_extract_all(fax[phoneset], "[0-9]{7,}")
ph_numbers <- unlist(ph_numbers)

```

```{r}

# Get duration of transmission
time_durations <- str_extract_all(fax[phoneset], "\\d{2}:\\d{2}:\\d{2}") # times for sending and duration
durations <- sapply(time_durations, function(x) x[length(x)])
durations <- period_to_seconds(hms(durations))
durations <- durations/60


```

```{r}
# Get pages transmitted
pages <- str_extract_all(fax[phoneset], "\\d+/\\d+") # pages
pages <- str_extract_all(pages, "\\d+")
pages <- sapply(pages, function(x) x[length(x)])
pages <- as.integer(pages)


```

```{r}
# Get baud rate
baud <- str_extract_all(fax[phoneset], "\\d+$")
baud <- as.integer(baud)


```

```{r}
# bind all into data frame
faxes <- data_frame(ph_numbers, durations, pages, baud)


```


```{r}
# hypothesis: the speed is worse for certain numbers
faxes %>% filter(pages > 0) %>% 
  mutate(min_per_page = durations/pages) %>%
  group_by(ph_numbers) %>% 
  summarize(tot_min = sum(durations), tot_pages = sum(pages)) %>% 
  mutate(avg_min_per_page = tot_min/tot_pages) %>% 
  arrange(desc(avg_min_per_page))
```

```{r}
# hypothesis: baud affects speed
faxes <- faxes %>% filter(pages > 0) %>%   
  mutate(min_per_page = durations/pages)

faxes %>% ggplot(aes(x = as.factor(baud), y = min_per_page)) + geom_boxplot()

t.test(min_per_page ~ baud, faxes)

faxes %>% 
  group_by(baud) %>% 
  summarize(avg_min_per_page = mean(min_per_page), sd_mpp = sd(min_per_page))



  summarize(tot_min = sum(durations), tot_pages = sum(pages)) %>% 
  mutate(avg_min_per_page = tot_min/tot_pages)
```

