---
title: Effects of Mangrove Clearance on Water Quality at He'eia Fishpond
author: ~
date: '2019-03-15'
slug: heeia
categories: 
  - R
tags: 
  - observation
  - ecology
subtitle: ''
---

```{r}
library(googlesheets)
suppressPackageStartupMessages(library(dplyr))
library(ggplot2)
```

```{r, cache = F}
# Change cache flag to F if updating data
my_sheets <- gs_ls()
fb <- gs_title("heeia")
x <- gs_read(fb)
```

```{r}
x <- as_tibble(x)
x
```

# Description of Mean Dissolved Oxygen, pH, and Turbidity by Mangrove Presence
```{r}
obs <- 9

x %>% group_by(mangrove) %>% 
  summarize(mean.DO = mean(DO),
            se.DO = sd(DO)/sqrt(obs),
            mean.pH = mean(pH),
            se.pH = sd(pH)/sqrt(obs),
            mean.turbidity = mean(turbidity),
            se.turbidity = sd(turbidity)/sqrt(obs))
```

# t-Tests
## Dissolved Oxygen by Mangrove Presence
```{r}
t.test(x$DO ~ x$mangrove)
```

```{r}
x %>% group_by(mangrove) %>% summarize(
  mean.DO = mean(DO), 
  se.DO = sd(DO)/sqrt(obs)
  ) %>%   
  ggplot(aes(x = mangrove, y = mean.DO, fill = mangrove)) + 
  geom_bar(stat='identity') +
  geom_errorbar(aes(ymin = mean.DO - se.DO, ymax = mean.DO + se.DO),
                width = 0.2,
                position=position_dodge(0.9))

```

## pH by Mangrove Presence
```{r}
t.test(x$pH ~ x$mangrove)
```

```{r}
x %>% group_by(mangrove) %>% summarize(
  mean.pH = mean(pH), 
  se.pH = sd(pH)/sqrt(obs)
  ) %>%   
  ggplot(aes(x = mangrove, y = mean.pH, fill = mangrove)) + 
  geom_bar(stat='identity') +
  geom_errorbar(aes(ymin = mean.pH - se.pH, ymax = mean.pH + se.pH),
                width = 0.2,
                position=position_dodge(0.9))
```

## Turbidity by Mangrove Presence
```{r}
t.test(x$turbidity ~ x$mangrove)
```

```{r}
x %>% group_by(mangrove) %>% summarize(
  mean.turbidity = mean(turbidity), 
  se.turbidity = sd(turbidity)/sqrt(obs)
  ) %>%   
  ggplot(aes(x = mangrove, y = mean.turbidity, fill = mangrove)) + 
  geom_bar(stat='identity') +
  geom_errorbar(aes(ymin = mean.turbidity - se.turbidity, 
                    ymax = mean.turbidity + se.turbidity),
                width = 0.2,
                position=position_dodge(0.9))
```

## Multivariable Model for Dissolved Oxygen
Including date and mangrove as predictor variables.
```{r}
model1 <- lm(x$DO ~ x$mangrove + as.factor(x$Date))
summary(model1)
```

